#include <QMap>
#include <QPair>
#include <QFile>
#include <QList>
#include <QTime>
#include <QtGui>
#include <QDebug>
#include <QLineF>
#include <QImage>
#include <QColor>
#include <QString>
#include <QPointF>
#include <QObject>
#include <QVector>
#include <QWindow>
#include <QPrinter>
#include <QtOpenGL>
#include <QSplitter>
#include <QMimeData>
#include <QFileInfo>
#include <QVector4D>
#include <QVector3D>
#include <QVector2D>
#include <QTabWidget>
#include <QMatrix4x4>
#include <QTextStream>
#include <QMessageBox>
#include <QTreeWidget>
#include <QWheelEvent>
#include <QQuaternion>
#include <QStringList>
#include <QMainWindow>
#include <QPainterPath>
#include <QApplication>
#include <QOpenGLBuffer>
#include <QItemDelegate>
#include <QStateMachine>
#include <QGraphicsView>
#include <QGraphicsScene>
#include <QOpenGLContext>
#include <QSharedPointer>
#include <QProgressDialog>
#include <QGraphicsObject>
#include <QCoreApplication>
#include <QOpenGLFunctions>
#include <QGraphicsPathItem>
#include <QAbstractItemModel>
#include <QGraphicsItemGroup>
#include <QOpenGLDebugLogger>
#include <QOpenGLPaintDevice>
#include <QAbstractTableModel>
#include <QOpenGLFunctions_3_1>
#include <QOpenGLShaderProgram>
#include <QOpenGLVertexArrayObject>
#include <QStyleOptionGraphicsItem>
#include <QOpenGLFunctions_4_0_Core>
#include <QGraphicsSceneDragDropEvent>
#include <QtWidgets/QtWidgets>

//#include <dl_creationadapter.h>
#include <qcustomplot.h>

#include <assimp/cimport.h>
#include <assimp/postprocess.h>
#include <assimp/scene.h>
#include <assimp/matrix4x4.h>

#include <omp.h>
#include <memory>
#include <map>
#include <comdef.h>
#include <memory.h>
#include <tchar.h>
#include <string>
#include <vfw.h>
#include <cmath>
#include <algorithm>
#include <fstream>
#include <cassert>
#include <climits>
#include <iostream>
#include <cstdio>
#include <ctime>
#include <vector>
#include <utility>
#include <cstdlib>
#include <cfloat>
#include <sstream>
#include <iomanip>
#include <cstdarg>

#pragma message("     _Adding library: vfw32.lib" ) 
#pragma comment ( lib, "vfw32.lib")